import json

with open("data/skills.json") as f:
    skills = json.load(f)
with open("data/connectors.json") as f:
    connectors = json.load(f)

CATS = [
    dict(key="ux-design", label="UX Design", blurb="Visual and interaction design, canvas tools, tokens, and brand systems."),
    dict(key="system-design", label="System Design", blurb="Architecture, databases, cloud infrastructure, IaC, and security."),
    dict(key="engineering", label="Engineering", blurb="Code quality, version control, testing, debugging, and sandboxes."),
    dict(key="documentation", label="Documentation", blurb="Writing, diagramming, and knowledge management."),
    dict(key="automation", label="Automation", blurb="Workflow orchestration, scheduling, browsing, and operations."),
]

out = []
out.append("// Auto-generated by scripts/generate_data_js.py -- do not hand-edit.")
out.append(f"const CATEGORIES = {json.dumps(CATS, indent=2)};")
out.append(f"const SKILLS = {json.dumps(skills, indent=2)};")
out.append(f"const CONNECTORS = {json.dumps(connectors, indent=2)};")

with open("docs/data.js", "w") as f:
    f.write("\n\n".join(out) + "\n")

print(f"Wrote docs/data.js with {len(skills)} skills and {len(connectors)} connectors")
